const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('app/static/selfit/selfit.js','utf8');
function harness(api, restored={user:{}}){const screens=[],rendered=[],state={};const context=vm.createContext({state,api,authReady:Promise.resolve(restored),showScreen:n=>screens.push(n),playIntro(){},track(){},renderReport:p=>{if(!p?.typeId)throw Error('missing');rendered.push(p);state.currentReportTypeId=p.typeId;}});vm.runInContext(source.slice(source.indexOf('  let currentReportRequest = null;'),source.indexOf("  document.querySelector('#reportLoadRetry')"))+'\nglobalThis.restore=restoreCurrentReport;',context);return {context,screens,rendered,state};}
test('loading never supplies a default persona and concurrent restores share a request',async()=>{let resolve;const pending=new Promise(r=>resolve=r);let calls=0;const h=harness({getLatestReport:async()=>{calls++;return {report:{reportId:'real'}};},getReport:()=>pending});const a=h.context.restore(),b=h.context.restore();assert.equal(a,b);await Promise.resolve();assert.deepEqual(h.rendered,[]);assert.deepEqual(h.screens,['loading']);resolve({report:{typeId:'loop'}});await a;assert.equal(calls,1);assert.equal(h.state.reportId,'real');assert.deepEqual(h.screens,['loading','report']);assert.equal(h.rendered[0].typeId,'loop');});
test('invalid payload and network failure show retry screen; retry can recover',async()=>{let fail=true;const h=harness({getLatestReport:async()=>({report:{reportId:'real'}}),getReport:async()=>fail?{report:{}}:{report:{typeId:'loop'}}});await h.context.restore();assert.equal(h.screens.at(-1),'report-error');assert.equal(h.rendered.length,0);fail=false;await h.context.restore();assert.equal(h.screens.at(-1),'report');});
test('normal startup does not render mute; report entry guards missing data',()=>{assert(!source.includes("renderReport(window.__SELFIT_REPORT__ || { typeId: 'mute' })"));assert(source.includes("name === 'report' && !state.currentReportTypeId"));});

test('login completed after an anonymous startup can restore its report',async()=>{const h=harness({getLatestReport:async()=>({report:{reportId:'real'}}),getReport:async()=>({report:{typeId:'loop'}})},null);h.state.authUser={user_id:'signed-in'};await h.context.restore();assert.equal(h.screens.at(-1),'report');});
test('network error shows retry without rendering a fallback',async()=>{const h=harness({getLatestReport:async()=>{throw Error('offline');}});await h.context.restore();assert.equal(h.screens.at(-1),'report-error');assert.equal(h.rendered.length,0);});
