const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('app/static/selfit-tryon/studio.js','utf8');
const start=src.indexOf('  function transformBuilderDrag('),end=src.indexOf('  $("#studio").addEventListener',start);
const ctx={};vm.createContext(ctx);vm.runInContext(src.slice(start,end),ctx);
const d={box:{x:25,y:25,w:50,h:50,rotation:20},mode:'scale',cx:100,cy:100,distance:50};
let b=ctx.transformBuilderDrag(d,175,100);assert.equal(b.w,75);assert.equal(b.x,12.5);assert.equal(b.h,75);
b=ctx.transformBuilderDrag(d,125,100);assert.equal(b.w,25);assert.equal(b.x,37.5);
b=ctx.transformBuilderDrag(d,1000,100);assert.equal(b.w,100);assert.equal(b.x,0);
b=ctx.transformBuilderDrag({...d,mode:'rotate',angle:0},100,150);assert.equal(b.rotation,110);assert.equal(b.w,50);
assert.equal(d.box.rotation,20);assert.equal(d.box.w,50);
console.log('Canvas drag scaling, rotation, bounds and original-state preservation passed');
