#!/usr/bin/env python3
"""Register six content-inspected winter dress families for browse diversity."""
from __future__ import annotations
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from scripts.build_selfit_aw_generated_garment_batch import build,stable_write
from scripts.prepare_selfit_garment_asset import prepare
AUDIT=ROOT/"docs/audits/20260904-aw-supply/generated-garments/batch08"; STATIC=ROOT/"app/static/selfit/assets/content_v2_drafts/aw-targeted-06/garments"; SRC=Path("/Users/yuanzexiang/.codex/generated_images/01a056c3-ad43-77d1-aed3-35866995a6d6")
SPECS=[
 {"slug":"winter-dress-pastel-iced","token":"n0042","id":"garment_aw_targeted06_dress_iced_pastel_01","name":"冰雾蓝窄长针织裙","category":"dress","layer_role":"single","tryon_slot":"dress","prompt":"Powder-blue opaque compact-knit precise column winter midi dress.","personas":["ICED","MUTE","LOOP"],"palette":"pastel","fit":"合体","silhouette":["narrow_column","clean_vertical","high_coverage"],"observation":{"subcategory":"precise_column_knit_midi_dress","neckline":"high_crew","sleeve":"long","length":"midi","volume":"narrow_straight","construction":"single_vertical_seam","pattern":"solid","decoration":"minimal","material_appearance":"opaque_compact_knit","main_colors":["powder_blue"]},"evidence":"冰雾蓝针织裙以高覆盖、窄长轮廓和低装饰表达收净冷感。","targets":["ICED×pastel×winter"],"source_output":str(SRC/"exec-340ed118-0641-4ae5-8047-34bbfe1524a8.png")},
 {"slug":"winter-dress-jewel-wabi","token":"n0043","id":"garment_aw_targeted06_dress_wabi_jewel_01","name":"深青弧线茧形针织裙","category":"dress","layer_role":"single","tryon_slot":"dress","prompt":"Deep-teal opaque textured-knit WABI cocoon winter midi dress.","personas":["WABI","VOID","EASE"],"palette":"jewel","fit":"宽松","silhouette":["gentle_cocoon","quiet_curved_seam","covered_column"],"observation":{"subcategory":"curved_seam_cocoon_knit_dress","neckline":"restrained_stand","sleeve":"long","length":"midi","volume":"gentle_cocoon","construction":"single_curved_seam","pattern":"solid","decoration":"minimal","material_appearance":"opaque_textured_knit","main_colors":["deep_teal"]},"evidence":"深青针织裙用单一弧线和受控茧形表达自然体积，没有拼布或破碎装饰。","targets":["WABI×jewel×winter"],"source_output":str(SRC/"exec-6e0c0b3c-bae7-4302-84ea-5460a85bff07.png")},
 {"slug":"winter-dress-jewel-heir","token":"n0044","id":"garment_aw_targeted06_dress_heir_jewel_01","name":"祖母绿经典衬衫裙","category":"dress","layer_role":"single","tryon_slot":"dress","prompt":"Deep-emerald classic long-sleeve defined-waist winter shirt midi dress.","personas":["HEIR","JADE","BOLT"],"palette":"jewel","fit":"合体","silhouette":["defined_waist","clean_shoulder","straight_a_line"],"observation":{"subcategory":"classic_shirt_a_line_midi_dress","neckline":"shirt_collar","sleeve":"long","length":"midi","volume":"straight_a_line","construction":"button_placket_defined_waist","pattern":"solid","decoration":"low","material_appearance":"opaque_wool_crepe_like","main_colors":["deep_emerald"]},"evidence":"祖母绿衬衫裙以经典领型、明确腰线和整洁 A 线形成秩序感。","targets":["HEIR×jewel×winter"],"source_output":str(SRC/"exec-92667174-01f5-4cd1-a1fa-04348eb427f5.png")},
 {"slug":"winter-dress-pastel-heir","token":"n0045","id":"garment_aw_targeted06_dress_heir_pastel_01","name":"灰玫瑰简洁收腰针织裙","category":"dress","layer_role":"single","tryon_slot":"dress","prompt":"Dusty-rose sophisticated defined-waist opaque winter midi dress.","personas":["HEIR","MELT","MUTE"],"palette":"pastel","fit":"合体","silhouette":["defined_waist","modest_v","soft_straight"],"observation":{"subcategory":"tailored_knit_midi_dress","neckline":"modest_v","sleeve":"long","length":"midi","volume":"soft_straight","construction":"tailored_waist_seams","pattern":"solid","decoration":"minimal","material_appearance":"opaque_dense_knit","main_colors":["dusty_rose"]},"evidence":"灰玫瑰针织裙用克制 V 领和经典腰部分割表达粉彩色，没有甜美装饰堆叠。","targets":["HEIR×pastel×winter"],"source_output":str(SRC/"exec-cbcfd632-e17f-464a-a881-2ceb2505b91c.png")},
 {"slug":"winter-dress-ocean-heir","token":"n0046","id":"garment_aw_targeted06_dress_heir_ocean_01","name":"深海蓝暗门襟经典衬衫裙","category":"dress","layer_role":"single","tryon_slot":"dress","prompt":"Deep-navy classic concealed-button defined-waist winter shirt dress.","personas":["HEIR","MUTE","ICED"],"palette":"ocean","fit":"合体","silhouette":["clean_defined_waist","long_vertical","classic_shirt"],"observation":{"subcategory":"concealed_placket_classic_shirt_dress","neckline":"small_shirt_collar","sleeve":"long","length":"midi","volume":"straight","construction":"concealed_buttons_clean_waistband","pattern":"solid","decoration":"minimal","material_appearance":"opaque_compact_woven","main_colors":["deep_navy"]},"evidence":"深海蓝衬衫裙的小领、暗门襟和平直腰线构成经典且日常的长线。","targets":["HEIR×ocean×winter"],"source_output":str(SRC/"exec-13d6f43c-3a8c-420e-b7c1-bfdfa9f6f0c2.png")},
 {"slug":"winter-dress-earth-ease","token":"n0047","id":"garment_aw_targeted06_dress_ease_earth_01","name":"暖驼抽绳松弛针织裙","category":"dress","layer_role":"single","tryon_slot":"dress","prompt":"Warm-camel relaxed but shaped opaque rib-knit winter midi dress.","personas":["EASE","LOOP","MELT"],"palette":"earth","fit":"宽松","silhouette":["soft_dropped_shoulder","subtle_draw_in","long_relaxed"],"observation":{"subcategory":"drawstring_rib_knit_midi_dress","neckline":"crew","sleeve":"long","length":"midi","volume":"relaxed_straight","construction":"subtle_waist_drawstring_side_slits","pattern":"solid","decoration":"minimal","material_appearance":"opaque_rib_knit","main_colors":["warm_camel"]},"evidence":"暖驼针织裙以落肩和长直松量表达舒展，细抽绳防止轮廓无边界。","targets":["EASE×earth×winter"],"source_output":str(SRC/"exec-d9eb552b-852c-41d0-a524-8a31a731e1e5.png")},
]
def main():
 for row in SPECS:
  source=Path(row["source_output"]); raw=AUDIT/"raw"/f"{row['slug']}-raw-v1.png"; prepared=AUDIT/"prepared"/f"{row['slug']}-v1.png"; qa=AUDIT/"qa"/f"{row['slug']}-v1.json"; stable_write(raw,source.read_bytes())
  if not prepared.exists(): report=prepare(raw,prepared); qa.parent.mkdir(parents=True,exist_ok=True); qa.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
 result=build(specs=SPECS,audit=AUDIT,static=STATIC,batch_id="aw-generated-garments-08",prompt_version="selfit-aw-winter-dress-family-v1"); result["binding_method"]="individual_order_binding_verified_by_contact_sheet"
 target=AUDIT/"manifest.json"
 if target.exists() and json.loads(target.read_text())!=result: raise SystemExit("Batch08 changed; refusing overwrite")
 target.write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n"); print(json.dumps({"version":result["version"],"garments":len(result["garments"]),"published":False},ensure_ascii=False))
if __name__=="__main__":main()
