#!/usr/bin/env python3
"""Compile native whole-image review for the lowest-condition long-outer batch."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];AUDIT=ROOT/"docs/audits/20260904-aw-supply";FIELDS=["axes","expression","formality","layering","persona_scores","scenes","seasons","structure","wearability","main_visual_slots","main_colors","conflicts","silhouette","color_relation","persona_evidence","winter_outdoor"]
def main():
 rendered=json.loads((AUDIT/"targeted-recipes.batch10.rendered.json").read_text());base=json.loads((ROOT/"app/data/recommendation-visual.v1.json").read_text());generated=json.loads((AUDIT/"generated-garments/batch11/manifest.json").read_text());visuals={**base["garments"],**generated["visual"]};entries=[]
 for pos,row in enumerate(rendered["entries"],1):
  raw=row["new_record"];obs=[visuals[x]["observations"] for x in raw["garment_ids"]];cats=[x["category"] for x in obs];structure="dress" if "dress" in cats else "skirt" if "skirt" in cats else "pants";season="winter" if "冬" in raw["season_tags"] else "autumn";colors=list(dict.fromkeys(c for x in obs if x["category"] not in {"shoes","bag"} for c in x.get("main_colors") or []));evidence=f"{raw['primary_persona']} 的目标色与轮廓由新长外层提供；{structure} 支撑款低竞争，主次、覆盖和闭合鞋关系可见。";observed={"axes":{},"expression":"typical","formality":"smart_casual","layering":2,"persona_scores":{raw["primary_persona"].lower():.86},"scenes":["daily"],"seasons":[season],"structure":structure,"wearability":"everyday_with_statement","main_visual_slots":["outer","dress"] if structure=="dress" else ["outer","top",structure],"main_colors":colors,"conflicts":None,"silhouette":f"reviewed_lowest_condition_{season}_{structure}","color_relation":"reviewed_coherent","persona_evidence":evidence,"winter_outdoor":"complete_layers_visually_reviewed" if season=="winter" else None};statuses={k:"unknown" if observed[k] is None else "ai_observed" for k in FIELDS};sheet=f"targeted-batch10-review/recipes-{(pos-1)//6+1}.jpg";prov={k:{"source_file":sheet,"version":"aw-targeted-10-native-v1","confidence":None if statuses[k]=="unknown" else .86} for k in FIELDS};entries.append({"outfit_id":raw["id"],"status":"ai_candidate","record_fingerprint":row["record_fingerprint"],"asset_sha256":row["asset_sha256"],"image_url":raw["assets"]["image_url"],"source_kind":"codex_visual_review","evidence":evidence,"observations":observed,"confidence":.86,"model":"current_codex_session","prompt_version":"aw-targeted-10-native-v1","review_level":"individual_contact_sheet_judgment","evidence_scope":"nonblind_individual_visual_judgment; no temperature/waterproof claim","review_complete":True,"field_status":statuses,"field_provenance":prov})
 assert len(entries)==48
 result={"schema_version":1,"source_rendered_version":rendered["version"],"independent_blind_review":False,"winter_outdoor_reviewed":True,"physical_warmth_verified":False,"entries":entries};result["version"]="aw-targeted-review-"+hashlib.sha256(json.dumps(result,sort_keys=True,ensure_ascii=False).encode()).hexdigest()[:20];target=AUDIT/"targeted-recipes.batch10.native-review.json"
 if target.exists() and json.loads(target.read_text())!=result:raise SystemExit("Review10 changed; refusing overwrite")
 target.write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n");print(json.dumps({"version":result["version"],"accepted":48,"held":0},ensure_ascii=False))
if __name__=="__main__":main()
